#!/bin/bash
#
# /etc/init.d/[[name]] -- startup script for [[name]]
#
### BEGIN INIT INFO
# Provides:     [[name]]
# Required-Start:  $time $network $remote_fs $syslog
# Required-Stop:   $time $network $remote_fs $syslog
# Default-Start:    2 3 4 5
# Default-Stop:     0 1 6
# Short-Description:    [[name]]
### END INIT INFO

. /lib/lsb/init-functions

PIDFILE="/var/run/[[name]].pid"

# Run [[name]] as this user ID and group ID
JMXTRANS_USER=[[name]]
JMXTRANS_GROUP=[[name]]

RUNCMD="/usr/share/[[name]]/jmxtrans.sh"

# overwrite settings from default file
if [ -f /etc/default/[[name]] ]; then
    set -a
    source /etc/default/[[name]]
    set +a
fi

RETVAL=0

do_start() {
    /usr/bin/touch "$PIDFILE" && /bin/chown "$JMXTRANS_USER":"$JMXTRANS_USER" "$PIDFILE"
    start-stop-daemon --start -b --pidfile $PIDFILE --oknodo \
        --chuid $JMXTRANS_USER:$JMXTRANS_GROUP -u $JMXTRANS_USER -g $JMXTRANS_GROUP -v \
        -d /usr/share/[[name]] --exec $RUNCMD -- start
    RETVAL=$?
}

do_stop() {
    su -m jmxtrans -c "$RUNCMD stop"
    RETVAL=$?
}

do_status() {
    su -m jmxtrans -c "$RUNCMD status"
    RETVAL=$?
}

case "$1" in
  start)
    log_daemon_msg "Starting [[name]]" "[[name]]"
    do_start
    log_end_msg $RETVAL
    ;;
  stop)
    log_daemon_msg "Stopping [[name]]" "[[name]]"
    do_stop
    log_end_msg $RETVAL
    ;;

  restart|reload|force-reload|try-restart)
    log_daemon_msg "Restarting [[name]]" "[[name]]"
    do_stop
    do_start
    log_end_msg $RETVAL
    ;;

  status)
    log_daemon_msg "Status [[name]]" "[[name]]"
    do_status
    log_end_msg $RETVAL
    ;;

  *)
    log_action_msg "Usage: /etc/init.d/[[name]] {start|stop|reload|force-reload|restart|try-restart|status}"
    exit 1
esac

exit $RETVAL
