language: java
sudo: false
before_install: git clone -b travis `git config --get remote.origin.url` ${HOME}/travis
services:
- docker
addons:
  apt:
    packages:
    - rpm
cache:
  directories:
  - "$HOME/.m2"
install:
- mvn compile -DskipTests=true -Dmaven.javadoc.skip=true -Dcobertura.skip=true -B
  -V
script: travis_wait 120 ./travis-script.sh
after_success:
- test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && mvn site
  site:stage scm-publish:publish-scm --settings ${HOME}/travis/settings.xml -B -V
branches:
  except:
  - travis
  - gh-pages
env:
  global:
  # GPG_PASSPHRASE
  - secure: "aVsw/zSi7VrW/rU5yzeCpL2aC09of8hgO12mASBW4jn8SXS6J3a9Vxx6bHHSNqWiBys/TTw4WSXv0QX2FU0hbMBUitw6wT5zMikLPJPoI57/JwbRG1kXvNKl1v2efP2wm04qlvJPhhUlzo/eIQJlWDE590sZ8lo8FdoDOx986cQ="
  # SONATYPE_USERNAME
  - secure: "c3AJ8jsBh3CwwyCQjGnCUGH2gDgX+n6OQdr4ec+z/fmdJbzVpen/JHFD6EoaN//mctOblRbT8tM0RCG47WtiFg7PCeXZsBvn5NkSuDgGjrCO3gVfvsdYwH1wkhPDEcwZGK6M29pA5gib/L2xrqhuYMmxzyjGQ08GmcS2yQrnhw4="
  # SONATYPE_PASSWORD
  - secure: "FyjSlx58Cl6xq44BCpHo2/bg9wZHIO7i1AU1T9TjxkQlyD+uqNjM49i6a8fzkyt6BDrKOtsruStD5pP/xqVBsGHMGmH+D4g5CXtlwfvTsCzuoElgJCOuiCNdDb+2R83uYOxQhTq7BtZUTyLky77B1nsBG6ANaU27JcpvYbSksh4="
  # GITHUB_TOKEN
  - secure: "RHBvhM5DFIIVmImN+p4Zg2n4bVKc9cXj9JeoXigxqo0ZRyuov5BSG1sgdaTh/l/h5CodvOwQH2hrpwlO9waw0Kg5fSiNoU2b3aCucA02LP1ks2ycsamusEsuJl+QStJ6ObQZLQ0zNoUOyS5HfhjM+7XPWK0FPlePkjHBS71fptE="
  # SONAR_TOKEN
  - secure: "cPeZQMtUxh6dpZNje5I3VaZT0joCIbH8ndX/pMRg53QhLrKuZrPC60HlSR0F+4Wx5c1B1YEZxaVy+u00gI5ObBauUOvPmRT8+5hCvnDQPtvGLvmSaQdrPv0O8XimlxwhxheYZka5AYwnglcMJ8qD/qK184j6B2ZXJvk9kgw7bn0="

