language: java
jdk:
  - openjdk8
sudo: false
before_install: git clone -b travis `git config --get remote.origin.url` ${HOME}/travis
services:
- docker
addons:
  apt:
    packages:
    - rpm
cache:
  directories:
  - "$HOME/.m2"
install:
- mvn compile -DskipTests=true -Dmaven.javadoc.skip=true -Dcobertura.skip=true -B
  -V
script: travis_wait 120 ./travis-script.sh
after_success:
- test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && mvn site
  site:stage scm-publish:publish-scm --settings ${HOME}/travis/settings.xml -B -V
branches:
  except:
  - travis
  - gh-pages
env:
  global:
  # GPG_PASSPHRASE
  - secure: "XxRmwFd7rzjtH9GJhmjy45evvs3wOIAihfChy91JBC1sFK+72b0YB6xx79csh+g8NIwAyWSpcbiCn2lCAlQqH8awI5LmozYtjCzUUHA5nvVtcAgPCHtXeVaslIoL0Hqvy2chtQXr4UuUFTYP8QDUGwk9EY8llgEfTlRIf2ZevDE="
  # SONATYPE_USERNAME
  - secure: "FvfjQW/OFbqzR5OLb97P+IFAtJERxUCDW6ki0AlsBDLjzBgax0qQ8CusXYL3UJDvcISpyZHzw91NePXPhUqsdZa9pKvIVQLNnPb87Kk25rv8iIhwMc1mtVyJG/QruMKUdFBTwGus2nXhPoFB4XcredAA/zqK3AoW6PmzL89PPRk="
  # SONATYPE_PASSWORD
  - secure: "Fp0Nu3c6GnXcsxbunuY5DTMvkWtGwBAqB3ZiCvUURMpgSpxA0pXXWs/cugy+NimI/Lkl2fPOx8lVuHcjm1FgW571PaeAzwE2AduZMgmuRtimcfrYodBLhW6b1pepI9VlWQ+NLZAk0VmAUjwQjEXDH7nAlGk5neUVZF11ZjS9jOk="
  # GITHUB_TOKEN
  - secure: "RHBvhM5DFIIVmImN+p4Zg2n4bVKc9cXj9JeoXigxqo0ZRyuov5BSG1sgdaTh/l/h5CodvOwQH2hrpwlO9waw0Kg5fSiNoU2b3aCucA02LP1ks2ycsamusEsuJl+QStJ6ObQZLQ0zNoUOyS5HfhjM+7XPWK0FPlePkjHBS71fptE="
  # SONAR_TOKEN
  - secure: "cSdkoZFcN0FCbbKJEnutGMmeIdvXuMnfR73v/2EFm4P5+uLfUdXxWHXKsjWiUYF8tP2/+rPSspuZ1qm9L27omW3JKyJYuaxwMY/KHr/LReyWAay/IruOkbNc9YZBGKOJShOHFrb1lBbAcsizRUrhN/qVD2u8yTp6VJvMKBAiDhE="
