# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # Every Vagrant virtual environment requires a box to build off of.
  config.vm.box = "puppetlabs/centos-6.5-64-nocm"

  # Share an additional folder where the full project is accessible
  config.vm.synced_folder "..", "/jmxtrans_src"

  config.vm.provision "shell", path: "build.sh"
  config.vm.provision "shell", inline: "yum install /jmxtrans_src/target/rpm/jmxtrans/RPMS/noarch/jmxtrans-*.rpm"

end
