#!/bin/bash

set -e

# Source debconf library.
. /usr/share/debconf/confmodule

# defaults file
CONFIG="/etc/default/[[name]]"

# get number of cores so we can set number of GC threads
CPU_CORES=$(cat /proc/cpuinfo | grep processor | wc -l)
NEW_RATIO=8

# defaults for JVM
HEAP_SIZE="512"

purge_line () {
    if [ -s "$1" ]; then
        # safely create a temp file
        t=$(tempfile) || exit
        trap "rm -f -- '$t'" EXIT

        # purge line
        sed "/$2/d" "$1" > "$t"
        mv "$t" "$1"

        # cleanup temp file
        rm -f -- "$t"
        trap - EXIT
    fi
}

sed_file () {
    # safely create a temp file
    t=$(tempfile) || exit
    trap "rm -f -- '$t'" EXIT

    sed "s/$1/$2/g" "$3" > "$t"
    mv "$t" "$3"

    # cleanup temp file
    rm -f -- "$t"
    trap - EXIT
}

case "$1" in
    configure)

        ##### deal with logs #####
        mkdir -p /var/log/[[name]]
        chown jmxtrans:jmxtrans /var/log/[[name]]

        if [ ! -d /usr/share/[[name]]/logs -a ! -h /usr/share/[[name]]/logs ]; then
            cd /usr/share/[[name]]
            ln -fs /var/log/[[name]] logs
        fi
        ##### deal with logs #####

        # collect user inputs
        db_get [[name]]/jvm_heap_size
        if [ ! -z "$RET" ]; then
            HEAP_SIZE="${RET}"
        fi

        HEAP_NUMBER=$(echo $HEAP_SIZE|sed 's/[a-zA-Z]//g')
        NEW_SIZE=$(expr $HEAP_SIZE / $NEW_RATIO)

        mkdir -p /var/lib/[[name]] || true
        chown jmxtrans:jmxtrans /var/lib/[[name]]

        # populate defaults file
        if [ ! -e "$CONFIG" ]; then
            echo "# default file for package [[name]]" > "$CONFIG"
            echo "export LOG_DIR=\"/var/log/[[name]]\"" >> "$CONFIG"
            echo "export SECONDS_BETWEEN_RUNS=60" >> "$CONFIG"
            echo "export JSON_DIR=\"/var/lib/[[name]]\"" >> "$CONFIG"
            echo "export HEAP_SIZE=${HEAP_SIZE}" >> "$CONFIG"
            echo "export NEW_SIZE=${NEW_SIZE}" >> "$CONFIG"
            echo "export CPU_CORES=${CPU_CORES}" >> "$CONFIG"
            echo "export NEW_RATIO=${NEW_RATIO}" >> "$CONFIG"
            echo "export LOG_LEVEL=debug" >> "$CONFIG"
        fi

        chmod 644 "${CONFIG}" || true
    ;;
    *)
        echo "postinst called with unknown argument \`$1'" >&2
    ;;
esac

if [ -x "/etc/init.d/jmxtrans" ]; then
        if [ ! -e "/etc/init/jmxtrans.conf" ]; then
                update-rc.d jmxtrans defaults >/dev/null
        fi  
        invoke-rc.d jmxtrans start || exit $?
fi


exit 0

