#!/bin/bash
#
# /etc/init.d/@PACKAGE -- startup script for @PACKAGE
#
### BEGIN INIT INFO
# Provides:     @PACKAGE@
# Required-Start:  $time $network $remote_fs $syslog
# Required-Stop:   $time $network $remote_fs $syslog
# Default-Start:    2 3 4 5
# Default-Stop:     0 1 6
# Short-Description:    @PACKAGE@
### END INIT INFO

. /lib/lsb/init-functions

PIDFILE="/var/run/@PACKAGE@.pid"

# Run @PACKAGE@ as this user ID and group ID
JMXTRANS_USER=@PACKAGE@
JMXTRANS_GROUP=@PACKAGE@

RUNCMD="/usr/share/@PACKAGE@/jmxtrans.sh"

# overwrite settings from default file
if [ -f /etc/default/@PACKAGE@ ]; then
    set -a
    source /etc/default/@PACKAGE@
    set +a
fi

RETVAL=0

do_start() {
    /usr/bin/touch "$PIDFILE" && /bin/chown "$JMXTRANS_USER":"$JMXTRANS_USER" "$PIDFILE"
    start-stop-daemon --start -b --pidfile $PIDFILE --oknodo \
        --chuid $JMXTRANS_USER:$JMXTRANS_GROUP -u $JMXTRANS_USER -g $JMXTRANS_GROUP -v \
        -d /usr/share/@PACKAGE@ --exec $RUNCMD -- start
    RETVAL=$?
}

do_stop() {
    su -m jmxtrans -c "$RUNCMD stop"
    RETVAL=$?
}

do_status() {
    su -m jmxtrans -c "$RUNCMD status"
    RETVAL=$?
}

case "$1" in
  start)
    log_daemon_msg "Starting @PACKAGE@" "@PACKAGE@"
    do_start
    log_end_msg $RETVAL
    ;;
  stop)
    log_daemon_msg "Stopping @PACKAGE@" "@PACKAGE@"
    do_stop
    log_end_msg $RETVAL
    ;;

  restart|reload|force-reload|try-restart)
    log_daemon_msg "Restarting @PACKAGE@" "@PACKAGE@"
    do_stop
    do_start
    log_end_msg $RETVAL
    ;;

  status)
    log_daemon_msg "Status @PACKAGE@" "@PACKAGE@"
    do_status
    log_end_msg $RETVAL
    ;;

  *)
    log_action_msg "Usage: /etc/init.d/@PACKAGE@ {start|stop|reload|force-reload|restart|try-restart|status}"
    exit 1
esac

exit $RETVAL
