#!/bin/sh

# If a specific java binary isn't specified search for the standard 'java' binary
if [ -z "$JAVACMD" ] ; then
  if [ -n "$JAVA_HOME"  ] ; then
    JAVACMD="$JAVA_HOME/bin/java"
  else
    JAVACMD=`which java`
  fi
fi

${JAVACMD} -Dlog4j.configuration=/etc/jmxtrans/log4j.xml ${JAVA_OPTS} -jar /usr/share/java/jmxtrans-all.jar "$@"
